# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.194.3/containers/alpine/.devcontainer/base.Dockerfile

FROM jekyll/jekyll

RUN gem install bundler:1.17.3

# ** [Optional] Uncomment this section to install additional packages. **
# RUN apk update \
#     && apk add --no-cache <your-package-list-here>
